server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/ms_user
spring.datasource.username=root
spring.datasource.password=ifsp
spring.jpa.hibernate.ddl-auto=update
spring.application.name=user

spring.rabbitmq.addresses=amqps://ocflwfhu:ecoqb2xR-l97BfeOEv8SlCCT6XKV_k0F@rattlesnake.rmq.cloudamqp.com/ocflwfhu
broker.queue.email.name=default.email